iOS Landscape Rotation
xamarin/XamarinCommunityToolkit pull request #1017
Opened 2021-03-04 10:36 UTC by JoelPickin

### Description of Change ###

- Register when the device is rotated by the OnElementPropertyChanged property of Height and Width. 
- When rotated set the bounds of the screen.
- When rotated set the camera orientation of the capture connection.

### Bugs Fixed ###
This previously was a bug I raised myself but was understandably changed to a feature-request.

https://github.com/xamarin/XamarinCommunityToolkit/issues/894

### API Changes ###

Added: 
 
- Added method in FormsCameraView.ios.cs: GetViewOrientation - Returns the AVCaptureVideoOrientation of the device.
- Added method in FormsCameraView.ios.cs: SetCameraOrientation - Sets the previewLayer.Connection.VideoOrientation to the AVCaptureVideoOrientation from GetViewOrientation and then assigned the previewLayer.Connection to captureConnection.

Changed:

 - In method InitializeCamerain FormsCameraView.ios.cs added the line previewLayer.Connection.VideoOrientation = GetViewOrientation(); to set the correct orientation when the camera is being initialized.
 - In CameraViewRenderer.ios.cs - Added cases to switch in method OnElementPropertyChanged to check when Height & Width are changed ti trigger Control.SetBounds(Element.Width, Element.Height); & Control.SetCameraOrientation();
 
### Behavioral Changes ###

Rotating the device from landscape to the opposite landscape flips the camera view as the renderer still doesn't register the difference in rotation change. Rotating from portrait to landscape, then to portrait and landscape again works fine. 

Images are captured in landscape also.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ * ] Has samples (if omitted, state reason in description) - Works in CameraView sample app
- [ * ] Rebased on top of main at time of PR
- [ * ] Changes adhere to coding standard

2021-03-12 00:54 UTC, pictos commented
@JoelPickin, can you rebase your PR against develop?

2021-03-16 12:04 UTC, JoelPickin commented
@pictos have done now. Thanks.

2021-03-23 01:16 UTC, AndreiMisiukevich commented
> @pictos have done now. Thanks.

something went wrong.
it seems you changed base branch on Github but didn't rebase in git

2021-03-23 11:11 UTC, JoelPickin commented
> > @pictos have done now. Thanks.
> 
> something went wrong.
> it seems you changed base branch on Github but didn't rebase in git

Sorry about this. I thought I had rebased correctly. I am having some issues building at the moment. I have tried pulling down a fresh version to look at trying again, but I am getting a lot of UWP errors.

2021-04-08 21:56 UTC, brminnick requested changes

2021-04-08 21:56 UTC, brminnick commented on azure-pipelines.yml
> +          solution: $(PathToCsproj)
Please revert all changes to `azure-pipelines.yml`

2021-04-22 08:42 UTC, JoelPickin commented
I'm going to close this PR and add my changes in a new branch and push that up as I'm not sure what the develop/rebase has done and feel it would be better starting fresh from the most recent.

2021-04-22 08:42 UTC, closed without merging

2021-04-22 09:22 UTC, JoelPickin commented
New PR https://github.com/xamarin/XamarinCommunityToolkit/pull/1224