Allow `null` to be passed as a parameter to `Execute` and `CanExecute` if the target is a `Nullable` type
xamarin/XamarinCommunityToolkit pull request #1356
Opened 2021-06-02 12:43 UTC by AmrAlSayed0

### Description of Change ###
Allow `null` to be passed as a parameter to `Execute` and `CanExecute` if the target is a `Nullable` type
### Bugs Fixed ###
- Fixes #1355
### API Changes ###
None
Added: 
- None
Changed:
 - None
### Behavioral Changes ###
`AsyncCommand`s and `AsyncValueCommand`s will now excute if a null is passed when their generic types are nullable.

### PR Checklist ###
- [x] Has a linked Issue, and the Issue has been `approved`
- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

2021-06-02 18:54 UTC, brminnick commented
Thanks @AmrAlSayed0!

Could you add some unit tests for this a well?

2021-06-02 19:15 UTC, brminnick requested changes
Looks good! Let's just add a couple unit tests for nullable value types before merging 👍

2021-06-04 12:52 UTC, AmrAlSayed0 commented
@brminnick Done.

2021-06-04 15:41 UTC, brminnick approved these changes

2021-06-04 15:59 UTC, merged