bugfix: return the path of video file with data
xamarin/XamarinCommunityToolkit pull request #356
Opened 2020-10-02 13:36 UTC by SABlyu

copy file path to local variable before calling re-initialization method, which override private class field with new file path (with zero data in it)

### Bugs Fixed ###
there was a bug, which prevented to get a genuine video file path on the upper level of camera view. 
here is the bug report: https://github.com/xamarin/XamarinCommunityToolkit/issues/355
- Fixes #
save the path of the file with data to a local variable to return it when the data is there
### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

2020-10-02 13:37 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=356) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=356) before we can accept your contribution.<br/><br/>:x: SABlyu [sign now](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=356)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/XamarinCommunityToolkit?pullRequest=356) it.</sub>

2020-10-06 12:53 UTC, jfversluis commented
Looks like it's failing to build: 

> XamarinCommunityToolkit\Views\CameraView\Android\CameraFragment.android.cs(445,20): Error CS0103: The name 'fileName' does not exist in the current context

2020-10-08 19:16 UTC, jfversluis commented
@SABlyu could you please let us know if you're able to bring this home? Thanks!

2020-10-19 00:54 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs
> +				capturedFile = fileName;
What is "fileName" here?

2020-11-04 08:53 UTC, jsuarezruiz requested changes
`fileName` not exists in that context, something is missing?

2020-11-29 10:25 UTC, AndreiMisiukevich commented
Closing this PR due to not having a response from the author for a long time.
Also, this PR has a compile error.

2020-11-29 10:25 UTC, closed without merging