Implemented the ContentButton
xamarin/XamarinCommunityToolkit pull request #386
Opened 2020-10-07 15:58 UTC by levelfivecoder

### Description of Change ###

Xamarin forms Button control is limited to text and icon. Usually we used to create components with Frame or Grid if we require a to define a Button with complex template.

## Features ##

- A new button control that is capable of adding UI templates
- CornerRadius & BorderColor
- Clicked event & Command

##API Changes##

Using the control
Create an instance for the ContentButton control

```
<views:ContentButton Margin="{StaticResource ContentPadding}"
                CornerRadius="8"
                Clicked="ContentButton_Clicked"
                BackgroundColor="White"
                BorderColor="#8a8a8a">
            <views:ContentButton.Content>
                <Grid ColumnSpacing="20">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="12" />
                        <ColumnDefinition Width="*" />
                    </Grid.ColumnDefinitions>
                    <BoxView BackgroundColor="#00ab64" />
                    <StackLayout Grid.Column="1" Padding="0,24,24,24"
                            Spacing="8">
                        <Label Style="{StaticResource label_section_header}"
                                Text="Button Title" />
                        <Label Text="Button description" />
                    </StackLayout>
                </Grid>
            </views:ContentButton.Content>
        </views:ContentButton>
```

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [✔]  Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [✔]  Changes adhere to coding standard

2020-10-07 21:29 UTC, VladislavAntonyuk commented on XamarinCommunityToolkitSample/Resx/AppResources.es.resx
> +    <value>ContentButton alows you to add content view to a button</value>
typo allows

2020-10-07 21:29 UTC, VladislavAntonyuk commented on XamarinCommunityToolkitSample/Resx/AppResources.resx
> +    <value>ContentButton alows you to add content view to a button</value>
typo allows

2020-10-09 00:00 UTC, AndreiMisiukevich requested changes
Hm @Char0394 could you please take a look at this PR
We have something similar https://github.com/xamarin/XamarinCommunityToolkit/blob/main/XamarinCommunityToolkit/Behaviors/Animations/AnimationBehavior.shared.cs

2020-10-09 13:04 UTC, levelfivecoder commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		ContentView contentHolder;
removed contentHolder

2020-10-09 13:05 UTC, levelfivecoder commented on XamarinCommunityToolkitSample/Xamarin.CommunityToolkit.Sample.csproj
>    <ItemGroup>
revert back to the old file

2020-10-09 13:06 UTC, levelfivecoder commented on XamarinCommunityToolkitSample/Pages/Views/ContentButtonPage.xaml.cs
> +		async void ContentButton_Clicked(System.Object sender, System.EventArgs e)
Removed button click in page code behind and implemented command binding with viewmodel (included the counter)

2020-10-09 13:06 UTC, levelfivecoder commented on XamarinCommunityToolkitSample/Pages/Views/ContentButtonPage.xaml.cs
> +			var result = await this.DisplaySnackbar(AppResources.ContentButtonTapMessage, 3000, "Run action", () =>
implemented Clicks counter

2020-10-09 13:07 UTC, levelfivecoder commented on XamarinCommunityToolkitSample/ViewModels/Views/ContentButtonViewModel.cs
> +	}
Added command and counter logics

2020-10-10 17:56 UTC, AndreiMisiukevich commented
Is there any advantage of this control over using AnimationBehavior with a Frame? 

https://github.com/xamarin/XamarinCommunityToolkit/blob/main/XamarinCommunityToolkit/Behaviors/Animations/AnimationBehavior.shared.cs

2020-10-13 21:44 UTC, domagojmedo commented
@AndreiMisiukevich to me this is much nicer syntax to use than AnimationBehavior. Also it doesn't seem intuitive to me that you should use AnimationBehaviour if you want to accomplish this

2020-10-14 05:49 UTC, levelfivecoder commented
> Is there any advantage of this control over using AnimationBehavior with a Frame?
> 
> https://github.com/xamarin/XamarinCommunityToolkit/blob/main/XamarinCommunityToolkit/Behaviors/Animations/AnimationBehavior.shared.cs

this provide a better syntax, instead of behaviour we can use as a VIew. Also we must think of animating the contentbutton by adding a bindable property with different animation options (This I require help)

2020-10-16 06:20 UTC, levelfivecoder commented
Any update on this?

2020-10-16 07:38 UTC, AndreiMisiukevich reviewed
Sorry for the delay

2020-10-16 07:38 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		public static readonly BindableProperty CornerRadiusProperty = BindableProperty.Create(nameof(CornerRadius), typeof(float), typeof(ContentButton), 0.0f, propertyChanged: OnCornerRadiusPropertyChang
```suggestion
		public static readonly BindableProperty CornerRadiusProperty 
			= BindableProperty.Create(nameof(CornerRadius), typeof(float), typeof(ContentButton), 0.0f, propertyChanged: OnCornerRadiusPropertyChanged);
```

2020-10-16 07:38 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		public static readonly BindableProperty BorderColorProperty = BindableProperty.Create(nameof(BorderColor), typeof(Color), typeof(ContentButton), Color.Default, propertyChanged: OnBorderColorPropert
```suggestion
		public static readonly BindableProperty BorderColorProperty 
			= BindableProperty.Create(nameof(BorderColor), typeof(Color), typeof(ContentButton), Color.Default, propertyChanged: OnBorderColorPropertyChanged);
```

2020-10-16 07:38 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		public static new readonly BindableProperty BackgroundColorProperty = BindableProperty.Create(nameof(BackgroundColor), typeof(Color), typeof(ContentButton), Color.Default, propertyChanged: OnBackgr
```suggestion
		public static new readonly BindableProperty BackgroundColorProperty = BindableProperty.Create(nameof(BackgroundColor), typeof(Color), typeof(ContentButton), Color.Default, propertyChanged: OnBackgroundColorPropertyChanged);
```
```suggestion
		public static new readonly BindableProperty BackgroundColorProperty 
			= BindableProperty.Create(nameof(BackgroundColor), typeof(Color), typeof(ContentButton), Color.Default, propertyChanged: OnBackgroundColorPropertyChanged);
```

2020-10-16 07:38 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		}
```suggestion
			=> Control.CornerRadius = CornerRadius;

		void OnBorderColorPropertyChanged()
			=> Control.BorderColor = BorderColor;

		void OnBackgroundColorPropertyChanged()
			=> Control.BackgroundColor = BackgroundColor;
```

2020-10-16 07:38 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +			Control.GestureRecognizers.Add(new TapGestureRecognizer
```suggestion
			control.Padding = 0;
			control.GestureRecognizers.Add(new TapGestureRecognizer
```

2020-10-16 07:38 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +			}
```suggestion
				Control.Content = Content;
```

2020-10-16 07:40 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +				Control.Content = Content;
```suggestion
				Control.Content = Content;
				
```

2020-10-16 07:45 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +					await Control.FadeTo(1, 100);
should be converted to single animation with two nested ones.

Child Animation: https://www.thewissen.io/playing-with-animation-in-xamarin-forms/
(the first animation will be from 0 to .5, the second one from .5 till 1. Animation time will be 200)

2020-10-16 07:46 UTC, AndreiMisiukevich submitted a review, later dismissed
Please fix merge conflicts

2020-10-17 13:04 UTC, levelfivecoder commented
> Please fix merge conflicts

conflicts resolved

2020-10-19 00:50 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +					await Control.FadeTo(1, 100);
I am sure it should be converted to a single animation

2020-11-04 08:46 UTC, jsuarezruiz commented
Sorry @levelfivecoder there are more conflicts. Could you fix the merge conflicts?. Let me know if need help with anything.

2020-11-05 16:22 UTC, levelfivecoder commented
> Sorry @levelfivecoder there are more conflicts. Could you fix the merge conflicts?. Let me know if need help with anything.

@jsuarezruiz Sorry I was busy with my office works and travel for the past two weeks, So I was not able to check this PR. I've resolved the merge conflicts. Please check

2020-11-08 16:08 UTC, YZahringer commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		public static readonly BindableProperty CornerRadiusProperty
[Frame.CornerRadius](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.frame.cornerradius?view=xamarin-forms) does not allow it. Maybe clip it with [RoundRectangleGeometry](https://github.com/xamarin/Xamarin.Forms/pull/11851)?

2020-11-11 09:14 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		public static readonly BindableProperty CornerRadiusProperty
It was introduced in XF 5.0
I guess, we support lower versions as well

2020-11-24 15:11 UTC, levelfivecoder commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +					await Control.FadeTo(0.75, 100);
Can we add animations in the next version, may be I need some help from others also.

2020-11-24 15:13 UTC, levelfivecoder commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +					await Control.FadeTo(0.75, 100);
> There is only `Pressed` animation defined, is there a plan to support `Hover` animation? Maybe based on [TouchEffect](https://github.com/AndreiMisiukevich/TouchEffect)?

Can we add animations in next versions?, may be i need some help from others. I've plans to create bindable property for  selection of animations using enum.

2020-11-24 15:15 UTC, levelfivecoder commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +					await Control.FadeTo(0.75, 100);
not right now, we can include in the future stages

2020-11-24 15:15 UTC, levelfivecoder commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		public static readonly BindableProperty CornerRadiusProperty
@AndreiMisiukevich Should we change?

2020-11-24 15:17 UTC, VladislavAntonyuk commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +		public static readonly BindableProperty CornerRadiusProperty
I saw a PR to update to XF 5.0, and looks like it is a plan for the future. Waiting for the stable release.

2021-02-12 13:22 UTC, jsuarezruiz commented
@levelfivecoder Could you rebase to fix the conflicts?

2021-04-06 14:43 UTC, Cfun1 commented
Is this pr still alive ?

2021-04-06 16:36 UTC, pictos commented
@levelfivecoder are you able to move this PR forward?

2021-04-06 17:32 UTC, levelfivecoder commented
> @levelfivecoder are you able to move this PR forward?

Sorry I was busy with my works in recent months, I had tried to rebase this branch. due to some conflicts I couldn't do that, Can someone rebase this?

2021-04-06 17:34 UTC, pictos commented
> > @levelfivecoder are you able to move this PR forward?
> 
> Sorry I was busy with my works in recent months, I had tried to rebase this branch. due to some conflicts I couldn't do that, Can someone rebase this?

Sure thing! But after sync will you be able to move this forward or should we do it?

2021-04-06 17:39 UTC, levelfivecoder commented
> > > @levelfivecoder are you able to move this PR forward?
> > 
> > 
> > Sorry I was busy with my works in recent months, I had tried to rebase this branch. due to some conflicts I couldn't do that, Can someone rebase this?
> 
> Sure thing! But after sync will you be able to move this forward or should we do it?

Thanks, hope I'll get some time. I really wanted to move forward with this PR

2021-04-06 18:40 UTC, pictos commented
> Thanks, hope I'll get some time. I really wanted to move forward with this PR

@levelfivecoder if you need anything, please let me know

2021-05-05 18:22 UTC, levelfivecoder commented
> > Thanks, hope I'll get some time. I really wanted to move forward with this PR
> 
> @levelfivecoder if you need anything, please let me know

HI Can you please follow up the PR, I'm too busy with my office works these days

2021-05-05 18:24 UTC, levelfivecoder commented
@pictos Can you please follow up the PR, I'm too busy with my office works these days

2021-05-06 00:47 UTC, pictos commented
@levelfivecoder sure thing, thanks for your work (:

2021-05-07 01:33 UTC, pictos commented
@levelfivecoder when you have time, can you give me context on what is missing?

2021-05-09 20:00 UTC, pictos commented on XamarinCommunityToolkit/Views/ContentButton.shared.cs
> +					await Control.FadeTo(0.75, 100);
@AndreiMisiukevich do you think that is a good idea to use the TouchEffect to handle the click action? Maybe I can refactor it and expose some props to devs.

2021-07-01 21:56 UTC, brminnick commented
Closing PR as it has been abandoned.

If anybody is interested in taking over this PR we are more than happy to re-open it!

2021-07-01 21:56 UTC, closed without merging