#474 Add setters to the snackbar options, #477 Snackbar default settings
xamarin/XamarinCommunityToolkit pull request #508
Opened 2020-10-28 19:45 UTC by VladislavAntonyuk

### Description of Change ###

Add setters to the snackbar options
Add Snackbar default settings

### Bugs Fixed ###
#474
#477 

### API Changes ###

Added: 
 
- static default properties for all options

Changed:

 - `ActionOptions` => `ToastOptions`
 - removed ctors for SnackBarOptions and ToastOptions. they were rather complex and required all options.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [x] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

2020-11-15 16:15 UTC, VladislavAntonyuk commented
@jfversluis, @AndreiMisiukevich could you please review? it has some breaking changes, it would be nice to fix them before release of stable version.

2020-11-15 16:52 UTC, AndreiMisiukevich submitted a review, later dismissed
Looks good
Only one question. Is it important to rename "ActionOptions => ToastOptions"?
If others are OK with such renaming, I am OK too

2020-11-15 17:15 UTC, VladislavAntonyuk commented
> Looks good
> Only one question. Is it important to rename "ActionOptions => ToastOptions"?
> If others are OK with such renaming, I am OK too

We use it with Toast. so ToastOptions is what user expect to use. ActionOptions is something really abstract. What is action for you? I think we should not associated it with Toast, SnackBar etc.

2020-11-15 17:19 UTC, pictos commented
I will review this until tomorrow.

2020-11-15 21:48 UTC, pictos requested changes
@VladislavAntonyuk nice work, as always! I have just some considerations about names, to make it more clear to our end users. Please let me know what do you think.

2020-11-15 21:48 UTC, pictos commented on XamarinCommunityToolkit/Views/SnackBar/Options/ToastOptions.shared.cs
> +		public int Duration { get; set; } = DefaultDuration;
Can we add the unit here, in the name of the property, or/and in the `summary` part?

2020-11-15 21:48 UTC, pictos commented on XamarinCommunityToolkit/Views/SnackBar/Options/ToastOptions.shared.cs
> +		public static int DefaultDuration { get; set; } = 3000;
Can we add the unit here? (ms, us, seconds)

2020-11-15 22:20 UTC, VladislavAntonyuk commented
> @VladislavAntonyuk nice work, as always! I have just some considerations about names, to make it more clear to our end users. Please let me know what do you think.

Thank you! I found that XF has Duration property of MediaElement. To be consistent with it I think we can leave it Duration. But what do you think if I change the type to TimeSpan?

2020-11-16 01:55 UTC, pictos commented
@VladislavAntonyuk I like the idea of TimeSpan.

2020-11-17 00:29 UTC, pictos approved these changes
![](https://media1.giphy.com/media/9g8PH1MbwTy4o/giphy.gif)

2020-11-17 12:17 UTC, AndreiMisiukevich approved these changes

2020-11-17 12:38 UTC, merged

2020-11-17 13:55 UTC, Tommigun1980 commented
Thank you so much once again @VladislavAntonyuk! Looks fantastic.