[Validation] MultiValidationBehavior with TextValidationBehavior : Regex init fix
xamarin/XamarinCommunityToolkit pull request #551
Opened 2020-11-12 14:26 UTC by Seuleuzeuh

### Description of Change ###

The method `OnRegexPropertyChanged()` was called in `OnAttachedTo` method but when a TextValidationBehavior (or one of his child) is used in MultiValidationBehavior this method was never called.
So `regex` property is never initialized and validation failed.

I've moved the call of OnRegexPropertyChanged in the ctor of the TextValidationBehavior.
I've added a sample for that case (Password validation sample using multiple CharactersValidationBehavior).

### Bugs Fixed ###

- Fixes #550 

### API Changes ###

Calling `OnRegexPropertyChanged()` on the ctor instead of in `OnAttachedTo`

### Behavioral Changes ###

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

2020-11-12 14:37 UTC, Seuleuzeuh commented
Adding simple tests for the MultiValidationBehavior for this particular use case (CharactersValidationBehavior inside a MultiValidationBehavior).

2020-11-12 14:39 UTC, jfversluis commented
Loving it, thank you so much!

2020-11-12 19:18 UTC, AndreiMisiukevich reviewed
Hello and thank you very much for your effort in making this lib a little better :)

I have a question. Don't you think it would make sense to apply this fix in MultiValidationBehavior

When a child is added we would call ```child.OnAttached()```
When a child is removed we would call ```child.OnDeattached()```

for achieving that, we would add a couple of new **internal virtual** methods to BaseValidationBehavior ```OnAttached``` and ```OnDeattached```

And we would use those methods in all places instead of **protected** ones

CC @jfversluis @pictos

I am fine with mergin it as is now as "hotfix" but I propose considering my idea

2020-11-12 19:27 UTC, Seuleuzeuh commented
That was my first idea at first, using the base interface IAttachedObject but it's Forms Internal so I've managed to moved the call. I've not thinking of call the base Beau of XCT instead, it's a great idea.
If you are ok with it, I can make the change.

2020-11-12 19:39 UTC, AndreiMisiukevich commented
> That was my idea at first, using the base interface IAttachedObject but it's Forms Internal so I've managed to moved the call. I've not thinking of call the base Behavior of XCT instead, it's a great idea.
> If you are ok with it, I can make the change.

if you wish, it would be great :)

2020-11-13 08:56 UTC, Seuleuzeuh commented
@AndreiMisiukevich It's done. Take a look and tell me if you thought the implementation like that.

2020-11-13 23:54 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Behaviors/BaseBehavior.shared.cs
>  		}
This method must contain all code that the currently **protected** method contains.
The protected method will be pretty slim

```csharp
protected override void OnAttachedTo(TView bindable)
{
	base.OnAttachedTo(bindable);
	OnAttached(bindable)
}
```

2020-11-13 23:55 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Behaviors/BaseBehavior.shared.cs
>  		}
The same for this method

2020-11-13 23:55 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Behaviors/Validators/MultiValidationBehavior.shared.cs
> +					child.OnAttached();
Yeah, exactly :)

2020-11-13 23:55 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Behaviors/Validators/MultiValidationBehavior.shared.cs
> +					child.OnDeattached();
👍

2020-11-13 23:57 UTC, AndreiMisiukevich commented on XamarinCommunityToolkit/Behaviors/Validators/TextValidationBehavior.shared.cs
> +
This file should contain only one change

```-``` ```protected override void OnAttachedTo(View bindable)```
```+``` ```internal override void OnAttached(View bindable)```

2020-11-14 00:10 UTC, AndreiMisiukevich requested changes
Actually, I think that a new internal method should appear inside ValidationBehavior instead of BaseBehavior.

Can we try to overwrite the old protected method with a new internal?

```csharp
internal new virtual void OnAttachedTo(TView bindable)
{
	base.OnAttachedTo(bindable);
	// Content
}
```

2020-11-14 00:27 UTC, AndreiMisiukevich requested changes
Well, I should apologize for the bad bits of advice.
I investigated code a little more and come up with the decision that your initial solution is the best fit for us.

Changes only in TextValidationBehavior
1) Remove OnAttachedTo overridden method
2) Add a constructor with OnRegexPropertyChanged invocation

Please ignore my other comments

2020-11-14 14:53 UTC, Seuleuzeuh commented
@AndreiMisiukevich Reverted changes to the initial PR code.

2020-11-14 16:28 UTC, AndreiMisiukevich approved these changes

2020-11-14 16:28 UTC, merged