MathOperationValueConverter - A converter that adds the ability to perform simple math operations
xamarin/XamarinCommunityToolkit pull request #617
Opened 2020-11-26 22:42 UTC by IeuanWalker

### Description of Change ###

Created a converter called `MathOperationValueConverter` that adds the ability to do a number of mathematical operations, such as -
- Add
- Minus
- Multiply
- Divide
- Remainder
- Exponent

The sample shows how it can be used to calculate perfectly rounder corners.

### Bugs Fixed ###
- Fixes #602 

### API Changes ###
Added: 
 
- New converter called `MathOperationValueConverter`

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

2020-11-26 23:12 UTC, AndreiMisiukevich commented
Is it actually related to #602?

2020-11-26 23:20 UTC, AndreiMisiukevich requested changes
Hi) Thank you very much for this contribution

But I am concerned about the implementation a little.

1) OperatorValue is double
2) The result of every operation is int (we cannot get 0.5 for example)

2020-11-26 23:20 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.Android/Xamarin.CommunityToolkit.Sample.Android.csproj
> -      <UserProperties XamarinHotReloadXFormsNugetUpgradeInfoBarXamarinCommunityToolkitSampleAndroidHideInfoBar="True" />
Please, discard

2020-11-26 23:20 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Xamarin.CommunityToolkit.Sample.csproj
> +    </Compile>
I believe, it can be removed

2020-11-26 23:20 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MathOperationValueConverter.shared.cs
> +	public enum OperatorEnum
It's better to move this enum to the own file )

2020-11-26 23:20 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MathOperationValueConverter.shared.cs
> +		Minus = 2,
Subtract

2020-11-26 23:20 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MathOperationValueConverter.shared.cs
> +		Unknown = 0,
None

2020-11-26 23:20 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MathOperationValueConverter.shared.cs
> +				_ => throw new ArgumentException(nameof(Operator)),
Do nothing in case of **None**

2020-11-26 23:20 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MathOperationValueConverter.shared.cs
> +		public double OperatorValue { get; set; }
```suggestion
		public OperatorEnum Operator { get; set; }
		
		public double OperatorValue { get; set; }
```

2020-11-26 23:24 UTC, pictos commented
I would like to discuss this feature a bit more, before moving this PR forward.

2020-11-27 00:44 UTC, pictos commented
@IeuanWalker as I wrote [here](https://github.com/xamarin/XamarinCommunityToolkit/issues/602#issuecomment-734518598) I'll close this PR for now, since we want something more close to the #237. You're more than welcome to contribute to the discussion and implementation when that feature is marked with the label `ready-to-implement`. Thanks again❣

2020-11-27 00:44 UTC, closed without merging