Solves [Bug] #595  Setting TabView.SelectedIndex does not "visually" switch tabs
xamarin/XamarinCommunityToolkit pull request #738
Opened 2021-01-09 08:48 UTC by Jouna77

Setting TabView.SelectedIndex does not "visually" switch tabs

### Description of Change ###
 Solves setting TabView.SelectedIndex does not "visually" switch tabs
Adding oldPosition value to UpdateSelectedIndex function in UpdateSelectedIndex avoids the false true on
` if (oldPosition == newPosition)`

### Bugs Fixed ###
https://github.com/xamarin/XamarinCommunityToolkit/issues/595
- Fixes #595

### API Changes ###

None

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`
- Parameter `oldPosition ` on `TabView.shared.UpdateSelectedIndex `

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

2021-01-09 08:48 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=738) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=738) before we can accept your contribution.<br/><br/>:x: Jouna77 [sign now](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=738)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/XamarinCommunityToolkit?pullRequest=738) it.</sub>

2021-01-09 11:00 UTC, jsuarezruiz approved these changes

2021-01-11 12:44 UTC, jsuarezruiz requested changes

2021-01-11 12:44 UTC, jsuarezruiz commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/TabView.shared.cs
> +		void UpdateSelectedIndex(int oldPosition, int position, bool hasCurrentItem = false)
Is it simpler perhaps, to validate the old and new index before invoking UpdateSelectedIndex?. Could you add an example where validate the fix?

2021-01-21 08:29 UTC, jfversluis approved these changes

2021-02-16 10:15 UTC, jfversluis commented
I think this is now solved by #903

2021-02-16 11:52 UTC, jfversluis commented
Maybe I was too quick on this 😬

2021-02-17 03:12 UTC, Jouna77 commented
Example forked and updated from: @MauricioCodeguez
https://github.com/Jouna77/TabViewDemo

2021-02-22 13:03 UTC, jfversluis approved these changes

2021-02-22 13:11 UTC, jfversluis approved these changes

2021-02-22 13:11 UTC, merged