Added new TextCaseType to TextCaseConverter
xamarin/XamarinCommunityToolkit pull request #763
Opened 2021-01-15 11:58 UTC by JoacimWall

Added support for first char to upper rest to lower case.

### Description of Change ###

Added new enum and logic for that enum to convert a string to first char to upper rest to lower case.

Sample No need for project sample i think:
<Label Text="{Binding Source={x:Static resource:AppResources.Logout}, Converter={StaticResource TextCaseConverter}, ConverterParameter={x:Static converters:TextCaseType.FirstUpperRestLower}}"/>

Regarding  PR check below i really don't know how to fix the rest check boxes. 
  ### Bugs Fixed ###

- Fixes #

### API Changes ###

None
Added: 
 
Added 
FirstUpperRestLower to the TextCaseType enum
Changed:

none

### Behavioral Changes ###

none

### PR Checklist ###

- [X] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

2021-01-15 12:02 UTC, AndreiMisiukevich commented
@JoacimWall please sign the CLA

2021-01-15 12:03 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs
> +
```suggestion
```

2021-01-15 12:06 UTC, AndreiMisiukevich requested changes
Please add unit tests (and perhaps update the sample app).

Current implementation causes the exception if string is empty or has 1 character

2021-01-15 15:50 UTC, JoacimWall commented
> Please add unit tests (and perhaps update the sample app).
> Added 
[InlineData(test, TextCaseType.FirstUpperRestLower, "Test")]
[InlineData(t, TextCaseType.FirstUpperRestLower, "T")]
[InlineData("", TextCaseType.FirstUpperRestLower, "")]
> Current implementation causes the exception if string is empty or has 1 character
Fixed only if string empty .1 char was working.

The project referens in xamarin.communityToolkit 
<ProjectReference Include="..\..\Markup\Xamarin.CommunityToolkit.Markup\Xamarin.CommunityToolkit.Markup.csproj" />  
does not match filesystem needed to change to ProjectReference Include="..\Markup...
to be able to run test. I don't check in this change.

2021-01-15 16:07 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs
> +				TextCaseType.FirstUpperRestLower => string.IsNullOrEmpty(value) ? string.Empty : value?.Substring(0, 1).ToUpperInvariant() + value?.Substring(1).ToLowerInvariant(),
```suggestion
				TextCaseType.FirstUpperRestLower => !string. IsNullOrWhiteSpace(value) 
					? value.Substring(0, 1).ToUpperInvariant() + value.Substring(1).ToLowerInvariant()
					: value
```

2021-01-15 16:07 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs
> +				TextCaseType.FirstUpperRestLower => !string. IsNullOrWhiteSpace(value)
```suggestion
				TextCaseType.FirstUpperRestLower => !string.IsNullOrWhiteSpace(value) 
```

2021-01-15 16:09 UTC, AndreiMisiukevich approved these changes

2021-01-15 20:52 UTC, sthewissen commented
I would perhaps rename the enum value to `FirstCharacterUppercase` as that already implies the rest is lowercase.

Furthermore, I wonder if this is meant to be something like TitleCase, which is actually culture dependant and can be done through a TextInfo object gathered from the current app culture?

2021-01-15 21:51 UTC, AndreiMisiukevich commented
> I would perhaps rename the enum value to `FirstCharacterUppercase` as that already implies the rest is lowercase.
> 
> Furthermore, I wonder if this is meant to be something like TitleCase, which is actually culture dependant and can be done through a TextInfo object gathered from the current app culture?

Title case sounds good, but just "FirstUpper" won't be enough (It sounds like "first upper and other as is")

2021-01-16 08:04 UTC, JoacimWall commented
> Please add unit tests (and perhaps update the sample app).
> 
> Current implementation causes the exception if string is empty or has 1 character

Ok

> I would perhaps rename the enum value to `FirstCharacterUppercase` as that already implies the rest is lowercase.
> 
> Furthermore, I wonder if this is meant to be something like TitleCase, which is actually culture dependant and can be done through a TextInfo object gathered from the current app culture?

Hi 
the ide is that if you have a string that is HELLO it should resoult in Hello. and if the input string is hello it should result in Hello.  In the app we use it we get strings from Resource file som time this string is HELLLO  then later som oe on desging says we need the samt string somewhere elles but this time it should be Hello then we dont want add an extra string to the resource file and all translations resurcefiles just use a converter. 

as you can se in the converter code it just not make the frist upper ot also make the rest lower 
value?.Substring(0, 1).ToUpperInvariant() + value?.Substring(1).ToLowerInvariant()
//Regards joacim

2021-01-16 18:24 UTC, pictos requested changes
Just a small observation (:

2021-01-16 18:24 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs
> +					: value
you missed the `,` 
```suggestion
					: value,
```

2021-01-16 19:56 UTC, AndreiMisiukevich commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs
> +					: value
It was my bad, I guess)

2021-01-16 20:11 UTC, pictos approved these changes
@JoacimWall Thank you for your contribution ❣

2021-01-16 20:20 UTC, merged

2021-02-23 14:17 UTC, JoacimWall commented
Hi 
One question when will the feature be in the release version?
//Regards Joacim

2021-02-23 22:54 UTC, AndreiMisiukevich commented
@JoacimWall I guess you can find it in the pre-release version of NuGet now.