[Android] Converting dimensions to pixels in popup renderer
xamarin/XamarinCommunityToolkit pull request #856
Opened 2021-02-07 23:28 UTC by geskill

### Description of Change ###

### Bugs Fixed ###

- Fixes #

### API Changes ###

### Behavioral Changes ###

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

2021-02-07 23:35 UTC, Cfun1 commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/Android/PopupRenderer.android.cs
> +				if (realContentHeight > -1)
Not sure if `realContentHeight ` will work fine as it was calculated based on `Element.Size.Width`, while here it was `Element.Content.HeightRequest`

2021-02-07 23:40 UTC, Cfun1 approved these changes

2021-02-07 23:40 UTC, Cfun1 commented
It looks good, tried it on the sample.

2021-02-08 00:09 UTC, pictos commented
@ahoefling can you take a look at this one, when it's ready for review?

2021-02-08 00:16 UTC, Cfun1 commented
@pictos can you rerun the checks from here, I think it an issue in Azure not the code

2021-02-08 00:19 UTC, pictos commented
@Cfun1 I don't believe that I have permission to trigger the build. The easiest way to do it is the author of the PR send a dumb commit

2021-02-08 00:42 UTC, ahoefling commented
@pictos can you assign me as a reviewer I'll take a look tomorrow morning. Checked from my phone and this appears to make sense

2021-02-08 00:44 UTC, pictos commented
@ahoefling for some reason I can't select your name :( 
@jfversluis can you assign Andrew as a reviewer of this PR?

2021-02-08 00:45 UTC, pictos commented
@ahoefling I can't assign you as a reviewer, but I can assign this PR to you, not sure if this makes GitHub notify you whatever this PR changes.

2021-02-08 14:43 UTC, ahoefling requested changes
The implementation looks great to me! Thank you so much for this because the Popup Size will be similar to iOS and UWP making any sizing math much easier.

When I first ran this in the sample app the popups were being drawn off screen because they were not updated. Please go back and update the sample code. Check all the popup.xaml files for a size and update accordingly. To make this easier there is a `PopupSize.cs` class with constants you can update. That isn't used in all popups, so you'll need to audit the rest.

Here is what it looks like unaltered
![image](https://user-images.githubusercontent.com/17751436/107234646-e0885d00-69f1-11eb-979d-0be4b6132647.png)

When I updated the size to `300x300` it looked like it did before. I would push the changes but I am not an official repo maintainer, so I'll need you or another maintainer to get in there and make this change

2021-02-08 14:49 UTC, ahoefling commented
This PR is missing the `Popup` label, can we have a maintainer add it

2021-02-08 16:56 UTC, geskill commented
I updated the `PopupSize.cs` definitions, like somehow mentioned here https://github.com/xamarin/XamarinCommunityToolkit/pull/839#issuecomment-774756295 .. now we have relative to screen size and fixed size examples.

2021-02-09 08:58 UTC, jfversluis commented
Let me know when this is ready to go according to you @ahoefling !

2021-02-09 22:29 UTC, ahoefling reviewed
This looks good to me and I think we are safe to merge. I am going to download the updates later tonight to do a final check before I approve the PR

2021-02-09 22:29 UTC, ahoefling commented on samples/XCT.Sample/Pages/Views/Popups/PopupSize.cs
> +		public static Size Medium => new Size(0.7 * (DeviceDisplay.MainDisplayInfo.Width / DeviceDisplay.MainDisplayInfo.Density), 0.6 * (DeviceDisplay.MainDisplayInfo.Height / DeviceDisplay.MainDisplayInf
I like this, great idea!

2021-02-10 03:10 UTC, ahoefling approved these changes
Just downloaded the code and everything looks good.

2021-02-10 03:37 UTC, pictos approved these changes

2021-02-10 03:37 UTC, merged