Add more animation behaviors
xamarin/XamarinCommunityToolkit pull request #898
Opened 2021-02-13 18:54 UTC by jsuarezruiz

### Description of Change ###

Added more animations behaviors: 

- BounceInAnimation and BounceOutAnimation
- ColorAnimation
- HeartAnimation
- RelRotateAnimation, RotateXAnimation and RotateYAnimation
- RelScaleAnimation
- TranslateAnimation
- TurnstileInAnimation and TurnstileOutAnimation

![more-animationsbehavior](https://user-images.githubusercontent.com/6755973/107858519-d244a180-6e34-11eb-934b-db7b72a92434.gif)

### API Changes ###

Changed `FlipHorizontalAnimation` and `FlipVerticalAnimation` classes to include `FlipDirection` property.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

2021-02-13 19:35 UTC, pictos requested changes
I suggest removing the async from Animates overrides, but if I'm missing something and they're needed, consider adding the ConfigureAwait(False) on those.

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/BounceAnimation.shared.cs
> +			await Task.Run(() =>
```suggestion
		public override Task Animate(View view) =>
			Task.Run(() =>
```

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/BounceAnimation.shared.cs
> +			await Task.Run(() =>
```suggestion
		public override Task Animate(View view) =>
			Task.Run(() =>
```

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/BounceAnimation.shared.cs
> +			await Task.Run(() =>
Also, I believe there's a property on Task.Run that makes it run on UI Thread, that way we don't need to call the `BeginInvokeOnMainThread´

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/ColorAnimation.shared.cs
> +			await Task.Run(() =>
```suggestion
		public override Task Animate(View view)
		{
			var fromColor = view.BackgroundColor;

			return Task.Run(() =>
```

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/FlipAnimation.shared.cs
> +            await Task.Run(() =>
```suggestion
        public override Task Animate(View view) =>
            Task.Run(() =>
```

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/FlipAnimation.shared.cs
> +            await Task.Run(() =>
```suggestion
        public override Task Animate(View view) =>
            Task.Run(() =>
```

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/HeartAnimation.shared.cs
> +            await Task.Run(() =>
```suggestion
        public override Task Animate(View view) =>
            Task.Run(() =>
```

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/RotateAnimation.shared.cs
> +            await view.RelRotateTo(Rotation, Duration, Easing);
```suggestion
        public override Task Animate(View view) =>
            view.RelRotateTo(Rotation, Duration, Easing);
```

2021-02-13 19:35 UTC, pictos commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/ColorExtension.shared.cs
> +        public static Task<bool> ColorTo(this VisualElement self, Color fromColor, Color toColor, Action<Color> callback, uint length = 250, Easing easing = null)
Can we change this to use ValueTask? Since we don't need to await anything? For the `ColorAnimationMethod` as well

2021-03-09 17:38 UTC, brminnick requested changes
Thanks Javier! 

For the `override Animate(View view)` methods, we can do two things to improve performance:
1. Remove the `async` keyword
  - The `async` keyword isn't necessary because we can return the `Task`
  - This prevents an unnecessary context (aka Thread) switch
2. Use `Device.InvokeOnMainThreadAsync`
  - Instead of using `Task.Run(() => Device.BeginInvokeOnMainThread...`, we can leverage `Device.InvokeOnMainThreadAsync` which does this for us; it enqueues a thread on the main thread in an asynchronous manner

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/BounceAnimation.shared.cs
> +			});
Let's replace this with 

```csharp
		public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.Animate("BounceIn", BounceIn(view), 16, Duration));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/BounceAnimation.shared.cs
> +			});
Let's replace this with 

```csharp
		public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.Animate("BounceOut", BounceOut(view), 16, Duration));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/ColorAnimation.shared.cs
> +			});
Let's replace this with 

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.ColorTo(fromColor, ToColor, c => view.BackgroundColor = c, Duration));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/FlipAnimation.shared.cs
> +            });
Let's replace this with 
```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.Animate("Flip", Flip(view), 16, Duration));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/FlipAnimation.shared.cs
> +
Let's replace this with

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.Animate("Flip", Flip(view), 16, Duration));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/HeartAnimation.shared.cs
> +            });
Let's replace this with 

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.Animate("Hearth", Hearth(view), 16, Duration));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/RotateAnimation.shared.cs
> +	}
All of the other `override Animate` methods push to the main thread. Should this push to the main thread too?

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.RelRotateTo(Rotation, Duration, Easing));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/RotateAnimation.shared.cs
> +            await view.RotateXTo(Rotation, Duration, Easing);
All of the other `override Animate` methods push to the main thread. Should this push to the main thread too?

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.RotateXTo(Rotation, Duration, Easing));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/ScaleAnimation.shared.cs
> +			await view.RelScaleTo(Scale, Duration, Easing);
All of the other `override Animate` methods push to the main thread. Should this push to the main thread too?

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.RelScaleTo(Scale, Duration, Easing));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/TranslateAnimation.shared.cs
> +            await view.TranslateTo(TranslateX, TranslateY, Duration, Easing);
All of the other `override Animate` methods push to the main thread. Should this push to the main thread too?

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.TranslateTo(TranslateX, TranslateY, Duration, Easing));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/TurnstileAnimation.shared.cs
> +            });
Let's change this to 

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.Animate("TurnstileIn", TurnstileIn(view), 16, Duration));
```

2021-03-09 17:38 UTC, brminnick commented on src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationTypes/TurnstileAnimation.shared.cs
> +            });
Let's replace this with

```csharp
public override Task Animate(View view) => Device.InvokeOnMainThreadAsync(() => view.Animate("TurnstileOut", TurnstileOut(view), 16, Duration));
```

2021-04-21 23:34 UTC, brminnick commented
@jsuarezruiz Can you take a look at fixing the merge conflicts?

2021-11-11 02:41 UTC, brminnick commented
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

2021-11-11 02:41 UTC, closed without merging